Repository CTStudyGroup/Programmers, pull requests merged in 2024-11, with the labels that each got.

#3 241106 : 큰 수 만들기 / Lv.2
  _eunjin/eunjin_큰_수_만들기.py
Labels: 그리디

#2 241106 : 큰 수 만들기 / Lv.2
  _hyeonji/hyeonji_큰 수 만들기
Labels: 브루트포스

#6 241107 : 소수 찾기 / Lv.2
  _eunjin/eunjin_소수_찾기.py
  _eunjin/eunjin_타겟_넘버.py
Labels: 조합, 순열, 브루트포스

#8 241108 : 타겟 넘버 / Lv.2
  _eunjin/eunjin_타겟_넘버.py
Labels: 브루트포스

#13 241111 : 의상 / Lv.2
  _hyeonji/hyeonji_의상.py
Labels: 브루트포스

#11 241111 : 의상 / Lv.2
  _eunjin/eunjin_의상.py
Labels: 조합

#14 241112 : H-Index / Lv.2
  _eunjin/eunjin_H-Index.py
Labels: 정렬

#16 241113 : 카펫 / Lv.2
  _eunjin/eunjin_카펫.py
Labels: 브루트포스

#19 241114 : 기능개발 / Lv.2
  _eunjin/eunjin_기능개발.py
Labels: 스택/큐

#20 241115 : N으로 표현 / Lv.3
  _eunjin/eunjin_N으로_표현.py
Labels: dp

#26 241118 : 피로도 / Lv.2
  _eunjin/eunjin_피로도.py
Labels: 브루트포스

#27 241119 : 네트워크 / Lv.3
  _eunjin/eunjin_네트워크.py
Labels: dfs & bfs

#28 241119 : 네트워크 / Lv.3
  _hyeonji/hyeonji_H-Index.py
  _hyeonji/hyeonji_네트워크.py
Labels: dfs & bfs

#29 241120 : 게임 맵 최단거리 / Lv.2
  _eunjin/eunjin_게임_맵_최단거리.py
Labels: dfs & bfs

#30 241120 : 게임 맵 최단거리 / Lv.2
  _hyeonji/hyeonji_게임 맵 최단거리.py
Labels: dfs & bfs

#31 241121 : 모음사전 / Lv.2
  _eunjin/eunjin_모음_사전.py
Labels: 순열

#32 241122 : 조이스틱 / Lv.2
  _eunjin/eunjin_조이스틱.py
Labels: 그리디
